site_name: Wholechain API Documentation
theme:
  name: material 
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.indexes
    - navigation.expantion
  language: en 
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime

extra:
  social:
    # - icon: fontawesome/brands/github-alt
    #   link: 
    # - icon: fontawesome/brands/twitter
    #   link: 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/wholechain
  footer: ''  # This removes the footer text

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="www.wholechain.com" target="_blank" rel="noopener">Wholechain</a>

nav:
  - Home:
    - Home/introduction.md
  - Getting Started:
    - Getting_Started/introduction.md 
    - Getting_Started/Authentication.md
    - Getting_Started/sandbox_setup.md
    - Getting_Started/example_requests.md
    - Getting_Started/error_codes.md
  - Events:
    - Commission: #Drop-Down
        - Introduction: Events/commission/introduction.md
        - Request Body: Events/commission/request body.md
        - Example Responses: Events/commission/example responses.md
    - Transform: #Drop-Down
        - Introduction: Events/Transform/introduction.md
        - Request Body: Events/Transform/request body.md
        - Example Responses: Events/Transform/example responses.md
  - Products (Coming Soon!): 
    - Products.md 
  - Locations (Coming Soon!):
    - Locations.md 
  - Help: 
    - Help.md 
  - Tesing:
    - index.md
  
  